### ISSUE TITLE
Graphql yoga PostgreSQL example not starting up

### ISSUE THREAD

**Issue by provpup** [genie-team/graphql-genie#13]
**Describe the bug**
Starting the server in the graphql yoga example (https://github.com/genie-team/graphql-genie/tree/master/examples/graphql-yoga-postgresql) results in `Cannot find module 'graphql'` webpack error for `graphql-genie-subscriptions`.

This is the error message seen:

`$ npm run start

> graphql-genie-postgresql-example@1.0.0 start /Users/nstudy/projects/graphql-genie/examples/graphql-yoga-postgresql
> node dist/index.js

webpack:///./node_modules/graphql-genie-subscriptions/lib_sync?:4
	throw e;
	^

Error: Cannot find module 'graphql'
    at webpackEmptyContext (webpack:///./node_modules/graphql-genie-subscriptions/lib_sync?:2:10)
    at eval (webpack:///./node_modules/graphql-genie-subscriptions/lib/subscriptions.js?:23:23)
    at eval (webpack:///./node_modules/graphql-genie-subscriptions/lib/subscriptions.js?:11:17)
    at eval (webpack:///./node_modules/graphql-genie-subscriptions/lib/subscriptions.js?:20:3)
    at Object../node_modules/graphql-genie-subscriptions/lib/subscriptions.js (/Users/nstudy/projects/graphql-genie/examples/graphql-yoga-postgresql/dist/index.js:2234:1)
    at __webpack_require__ (/Users/nstudy/projects/graphql-genie/examples/graphql-yoga-postgresql/dist/index.js:20:30)
    at eval (webpack:///./src/main.ts?:6:85)
    at Module../src/main.ts (/Users/nstudy/projects/graphql-genie/examples/graphql-yoga-postgresql/dist/index.js:5974:1)
    at __webpack_require__ (/Users/nstudy/projects/graphql-genie/examples/graphql-yoga-postgresql/dist/index.js:20:30)
    at /Users/nstudy/projects/graphql-genie/examples/graphql-yoga-postgresql/dist/index.js:84:18
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! graphql-genie-postgresql-example@1.0.0 start: `node dist/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the graphql-genie-postgresql-example@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nstudy/.npm/_logs/2018-09-04T21_44_20_324Z-debug.log
`

**To Reproduce**
Used node 8.11.4 LTS and npm 5.6.0
- `cd examples/graphql-yoga-postgresql`
- `npm install`
- `npm run build`
- `npm run start`

Attached is my package-lock.json file as a text file. 
[package-lock.json.txt](https://github.com/genie-team/graphql-genie/files/2350359/package-lock.json.txt)

**Expected behavior**
Server should have started up without errors.

**Screenshots**

**Desktop (please complete the following information):**
Using MacOS Sierra 10.12.6

**Additional context**

**Comment by acoreyj** [comment]
Thanks for opening the issue, looks like webpack doesn't like the subscriptions plugin format. I just published a fix.

You may have to run `npm upgrade graphql-genie-subscriptions`

**Comment by provpup** [comment]
Thanks @acoreyj !  It's working now 😄
